#!/bin/bash
# One-time (or re-run) setup for GoodCart on a Mac mini.
#
# Usage:
#   cd ~/agents/racing-agent/creator-food-store   # or your clone path
#   ./scripts/mac-mini-setup.sh
#
# Prerequisites: Node.js >= 20, pnpm 9 (installs pnpm via corepack if needed)
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_PATH="${ROOT}/packages/db/prisma/dev.db"
WEB_ENV="${ROOT}/apps/web/.env"
PORT="${PORT:-3000}"

cd "$ROOT"

echo "==> GoodCart Mac mini setup"
echo "    Root: $ROOT"

# --- Node / pnpm ---
if ! command -v node >/dev/null 2>&1; then
  echo "Node.js not found. Install Node 20+ from https://nodejs.org or via brew:" >&2
  echo "  brew install node@20" >&2
  exit 1
fi

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 20 ]]; then
  echo "Node.js >= 20 required (found $(node -v))." >&2
  exit 1
fi

if ! command -v pnpm >/dev/null 2>&1; then
  echo "==> Enabling pnpm via corepack"
  corepack enable
  corepack prepare pnpm@9.15.0 --activate
fi

echo "==> Installing dependencies"
pnpm install

# --- Env files ---
if [[ ! -f "$WEB_ENV" ]]; then
  echo "==> Creating apps/web/.env"
  AUTH_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)"
  cat > "$WEB_ENV" <<EOF
# Generated by scripts/mac-mini-setup.sh — edit as needed
DATABASE_URL="file:${DB_PATH}"
AUTH_SECRET="${AUTH_SECRET}"
AUTH_URL="http://localhost:${PORT}"
NEXT_PUBLIC_APP_URL="http://localhost:${PORT}"
NEXT_PUBLIC_APP_NAME="GoodCart"
EOF
  echo "    Wrote $WEB_ENV"
else
  echo "==> apps/web/.env already exists — leaving it alone"
  # Ensure DATABASE_URL points at absolute SQLite path if still relative
  if grep -q 'DATABASE_URL="file:\./' "$WEB_ENV" 2>/dev/null; then
    echo "    Warning: DATABASE_URL looks relative. Prefer:"
    echo "      DATABASE_URL=\"file:${DB_PATH}\""
  fi
fi

# Root .env for db package scripts
if [[ ! -f "${ROOT}/.env" ]]; then
  cp "$WEB_ENV" "${ROOT}/.env"
  echo "==> Copied .env to monorepo root"
fi

export DATABASE_URL="file:${DB_PATH}"

echo "==> Prisma generate + push + seed"
pnpm --filter @repo/db generate
pnpm --filter @repo/db push
pnpm --filter @repo/db seed

echo "==> Building web app"
pnpm --filter web build

mkdir -p "${ROOT}/logs"

echo
echo "Setup complete."
echo
echo "Run once (foreground):"
echo "  ./scripts/run-web.sh"
echo
echo "Install as LaunchAgent (survives reboot):"
echo "  ./launchd/install.sh"
echo
echo "Optional public URL via Cloudflare Tunnel:"
echo "  ./scripts/tunnel.sh"
echo
echo "Then open: http://localhost:${PORT}"
echo "  Storefront: http://localhost:${PORT}/@grocerygirl"
echo "  Discover:   http://localhost:${PORT}/discover"
